/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICheckInRegistry, ICheckInRegistryInterface } from "../../interfaces/ICheckInRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "isUsed",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ICheckInRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): ICheckInRegistryInterface {
      return new Interface(_abi) as ICheckInRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ICheckInRegistry {
      return new Contract(address, _abi, runner) as unknown as ICheckInRegistry;
    }
  }
  