/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITicketSystemState, ITicketSystemStateInterface } from "../../interfaces/ITicketSystemState.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "ownerOf",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "paused",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ITicketSystemState__factory {
    static readonly abi = _abi;
    static createInterface(): ITicketSystemStateInterface {
      return new Interface(_abi) as ITicketSystemStateInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITicketSystemState {
      return new Contract(address, _abi, runner) as unknown as ITicketSystemState;
    }
  }
  