/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICheckInRegistry } from './ICheckInRegistry.js';
export type { ITicketNFT } from './ITicketNFT.js';
export type { ITicketSystemState } from './ITicketSystemState.js';